name: rlp
description: An Ethereum RLP (Recursive Length Prefix) encoding library for Dart.
version: 2.0.0
homepage: https://github.com/maxholman/rlp

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  convert: ^3.0.1

dev_dependencies:
  test: ^1.20.1
  pointycastle: ^3.5.1
