name: rlp
description: An Ethereum RLP library for Dart.
version: 1.0.0
homepage: https://github.com/maxholman/rlp
author: Max Holman <max@holmn.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  convert: ^2.0.2

dev_dependencies:
  test: ^1.0.4
  pointycastle: 1.0.0-rc4
